// Package score provides support for scoring tests.
// It is intended to be used in concert with the Quickfeed web service,
// which automates execution and scoring of student implemented assignments
// aimed to pass a given set of tests.
//
// Quickfeed computes the score according to the formulas below, providing
// a percentage score for a test or a group of tests. The Weight parameter can
// be used to give more or less weight to some Score objects (representing
// different test sets). For example, if TestA has Weight 2 and TestB has Weight 1,
// then passing TestA gives twice the score of passing TestB.
//
// If you want to only give a score for completing a test, then you can simply
// use NewScoreMax(t, 1, 1), without using any API methods to decrement the score,
// giving a result of Score = MaxScore = 1 and Weight = 1.
//
// Quickfeed computes the final score as follows:
//   TotalWeight     = sum(Weight)
//   TaskScore[i]    = Score[i] / MaxScore[i], gives {0 < TaskScore < 1}
//   TaskWeight[i]   = Weight[i] / TotalWeight
//   TotalScore      = sum(TaskScore[i]*TaskWeight[i]), gives {0 < Score < 1}
//
// Quickfeed parses the output stream generated by an assignment's tests,
// looking for a JSON Score object whose Secret field matches the scoring
// session's secret value. If such a JSON Score object is found, Quickfeed
// extracts and records the Score object to be used in the above calculation.
// All other output is ignored when computing the score.
package score
