// Code generated by "stringer -type=role"; DO NOT EDIT.

package interceptor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[user-1]
	_ = x[group-2]
	_ = x[student-3]
	_ = x[teacher-4]
	_ = x[admin-5]
}

const _role_name = "noneusergroupstudentteacheradmin"

var _role_index = [...]uint8{0, 4, 8, 13, 20, 27, 32}

func (i role) String() string {
	if i < 0 || i >= role(len(_role_index)-1) {
		return "role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _role_name[_role_index[i]:_role_index[i+1]]
}
