coverage:
  status:
    project:
      default:
        target: 40%
        threshold: 1%
ignore:
  - "**/*.pb.go" # ignore generated protobuf files
  - "internal/env/auth_secret.go"
  - "cmd/**"
  - "main.go"
