coverage:
  status:
    project:
      default:
        target: 30%
        threshold: 10%
ignore:
  - "**/*.connect.go" # ignore generated protobuf files
  - "**/*.pb.go" # ignore generated protobuf files
  - "internal/env/auth_secret.go"
  - "cmd/**"
  - "main.go"
  - "internal/qtest/test_helper.go"
