services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 443:443
    volumes:
      - vol:/quickfeed
volumes:
  vol:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind
