// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: qf/qf.proto

package qf

import (
	context "context"
	types "github.com/quickfeed/quickfeed/qf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuickFeedServiceClient is the client API for QuickFeedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuickFeedServiceClient interface {
	GetUser(ctx context.Context, in *types.Void, opts ...grpc.CallOption) (*types.User, error)
	GetUsers(ctx context.Context, in *types.Void, opts ...grpc.CallOption) (*types.Users, error)
	GetUserByCourse(ctx context.Context, in *types.CourseUserRequest, opts ...grpc.CallOption) (*types.User, error)
	UpdateUser(ctx context.Context, in *types.User, opts ...grpc.CallOption) (*types.Void, error)
	IsAuthorizedTeacher(ctx context.Context, in *types.Void, opts ...grpc.CallOption) (*types.AuthorizationResponse, error)
	GetGroup(ctx context.Context, in *types.GetGroupRequest, opts ...grpc.CallOption) (*types.Group, error)
	GetGroupByUserAndCourse(ctx context.Context, in *types.GroupRequest, opts ...grpc.CallOption) (*types.Group, error)
	GetGroupsByCourse(ctx context.Context, in *types.CourseRequest, opts ...grpc.CallOption) (*types.Groups, error)
	CreateGroup(ctx context.Context, in *types.Group, opts ...grpc.CallOption) (*types.Group, error)
	UpdateGroup(ctx context.Context, in *types.Group, opts ...grpc.CallOption) (*types.Group, error)
	DeleteGroup(ctx context.Context, in *types.GroupRequest, opts ...grpc.CallOption) (*types.Void, error)
	GetCourse(ctx context.Context, in *types.CourseRequest, opts ...grpc.CallOption) (*types.Course, error)
	GetCourses(ctx context.Context, in *types.Void, opts ...grpc.CallOption) (*types.Courses, error)
	GetCoursesByUser(ctx context.Context, in *types.EnrollmentStatusRequest, opts ...grpc.CallOption) (*types.Courses, error)
	CreateCourse(ctx context.Context, in *types.Course, opts ...grpc.CallOption) (*types.Course, error)
	UpdateCourse(ctx context.Context, in *types.Course, opts ...grpc.CallOption) (*types.Void, error)
	UpdateCourseVisibility(ctx context.Context, in *types.Enrollment, opts ...grpc.CallOption) (*types.Void, error)
	GetAssignments(ctx context.Context, in *types.CourseRequest, opts ...grpc.CallOption) (*types.Assignments, error)
	UpdateAssignments(ctx context.Context, in *types.CourseRequest, opts ...grpc.CallOption) (*types.Void, error)
	GetEnrollmentsByUser(ctx context.Context, in *types.EnrollmentStatusRequest, opts ...grpc.CallOption) (*types.Enrollments, error)
	GetEnrollmentsByCourse(ctx context.Context, in *types.EnrollmentRequest, opts ...grpc.CallOption) (*types.Enrollments, error)
	CreateEnrollment(ctx context.Context, in *types.Enrollment, opts ...grpc.CallOption) (*types.Void, error)
	UpdateEnrollments(ctx context.Context, in *types.Enrollments, opts ...grpc.CallOption) (*types.Void, error)
	// Get latest submissions for all course assignments for a user or a group.
	GetSubmissions(ctx context.Context, in *types.SubmissionRequest, opts ...grpc.CallOption) (*types.Submissions, error)
	// Get lab submissions for every course user or every course group
	GetSubmissionsByCourse(ctx context.Context, in *types.SubmissionsForCourseRequest, opts ...grpc.CallOption) (*types.CourseSubmissions, error)
	UpdateSubmission(ctx context.Context, in *types.UpdateSubmissionRequest, opts ...grpc.CallOption) (*types.Void, error)
	UpdateSubmissions(ctx context.Context, in *types.UpdateSubmissionsRequest, opts ...grpc.CallOption) (*types.Void, error)
	RebuildSubmissions(ctx context.Context, in *types.RebuildRequest, opts ...grpc.CallOption) (*types.Void, error)
	CreateBenchmark(ctx context.Context, in *types.GradingBenchmark, opts ...grpc.CallOption) (*types.GradingBenchmark, error)
	UpdateBenchmark(ctx context.Context, in *types.GradingBenchmark, opts ...grpc.CallOption) (*types.Void, error)
	DeleteBenchmark(ctx context.Context, in *types.GradingBenchmark, opts ...grpc.CallOption) (*types.Void, error)
	CreateCriterion(ctx context.Context, in *types.GradingCriterion, opts ...grpc.CallOption) (*types.GradingCriterion, error)
	UpdateCriterion(ctx context.Context, in *types.GradingCriterion, opts ...grpc.CallOption) (*types.Void, error)
	DeleteCriterion(ctx context.Context, in *types.GradingCriterion, opts ...grpc.CallOption) (*types.Void, error)
	CreateReview(ctx context.Context, in *types.ReviewRequest, opts ...grpc.CallOption) (*types.Review, error)
	UpdateReview(ctx context.Context, in *types.ReviewRequest, opts ...grpc.CallOption) (*types.Review, error)
	GetReviewers(ctx context.Context, in *types.SubmissionReviewersRequest, opts ...grpc.CallOption) (*types.Reviewers, error)
	GetProviders(ctx context.Context, in *types.Void, opts ...grpc.CallOption) (*types.Providers, error)
	GetOrganization(ctx context.Context, in *types.OrgRequest, opts ...grpc.CallOption) (*types.Organization, error)
	GetRepositories(ctx context.Context, in *types.URLRequest, opts ...grpc.CallOption) (*types.Repositories, error)
	IsEmptyRepo(ctx context.Context, in *types.RepositoryRequest, opts ...grpc.CallOption) (*types.Void, error)
}

type quickFeedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuickFeedServiceClient(cc grpc.ClientConnInterface) QuickFeedServiceClient {
	return &quickFeedServiceClient{cc}
}

func (c *quickFeedServiceClient) GetUser(ctx context.Context, in *types.Void, opts ...grpc.CallOption) (*types.User, error) {
	out := new(types.User)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetUsers(ctx context.Context, in *types.Void, opts ...grpc.CallOption) (*types.Users, error) {
	out := new(types.Users)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetUserByCourse(ctx context.Context, in *types.CourseUserRequest, opts ...grpc.CallOption) (*types.User, error) {
	out := new(types.User)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetUserByCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateUser(ctx context.Context, in *types.User, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) IsAuthorizedTeacher(ctx context.Context, in *types.Void, opts ...grpc.CallOption) (*types.AuthorizationResponse, error) {
	out := new(types.AuthorizationResponse)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/IsAuthorizedTeacher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetGroup(ctx context.Context, in *types.GetGroupRequest, opts ...grpc.CallOption) (*types.Group, error) {
	out := new(types.Group)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetGroupByUserAndCourse(ctx context.Context, in *types.GroupRequest, opts ...grpc.CallOption) (*types.Group, error) {
	out := new(types.Group)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetGroupByUserAndCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetGroupsByCourse(ctx context.Context, in *types.CourseRequest, opts ...grpc.CallOption) (*types.Groups, error) {
	out := new(types.Groups)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetGroupsByCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) CreateGroup(ctx context.Context, in *types.Group, opts ...grpc.CallOption) (*types.Group, error) {
	out := new(types.Group)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateGroup(ctx context.Context, in *types.Group, opts ...grpc.CallOption) (*types.Group, error) {
	out := new(types.Group)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) DeleteGroup(ctx context.Context, in *types.GroupRequest, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetCourse(ctx context.Context, in *types.CourseRequest, opts ...grpc.CallOption) (*types.Course, error) {
	out := new(types.Course)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetCourses(ctx context.Context, in *types.Void, opts ...grpc.CallOption) (*types.Courses, error) {
	out := new(types.Courses)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetCourses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetCoursesByUser(ctx context.Context, in *types.EnrollmentStatusRequest, opts ...grpc.CallOption) (*types.Courses, error) {
	out := new(types.Courses)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetCoursesByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) CreateCourse(ctx context.Context, in *types.Course, opts ...grpc.CallOption) (*types.Course, error) {
	out := new(types.Course)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/CreateCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateCourse(ctx context.Context, in *types.Course, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateCourseVisibility(ctx context.Context, in *types.Enrollment, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateCourseVisibility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetAssignments(ctx context.Context, in *types.CourseRequest, opts ...grpc.CallOption) (*types.Assignments, error) {
	out := new(types.Assignments)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetAssignments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateAssignments(ctx context.Context, in *types.CourseRequest, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateAssignments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetEnrollmentsByUser(ctx context.Context, in *types.EnrollmentStatusRequest, opts ...grpc.CallOption) (*types.Enrollments, error) {
	out := new(types.Enrollments)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetEnrollmentsByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetEnrollmentsByCourse(ctx context.Context, in *types.EnrollmentRequest, opts ...grpc.CallOption) (*types.Enrollments, error) {
	out := new(types.Enrollments)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetEnrollmentsByCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) CreateEnrollment(ctx context.Context, in *types.Enrollment, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/CreateEnrollment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateEnrollments(ctx context.Context, in *types.Enrollments, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateEnrollments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetSubmissions(ctx context.Context, in *types.SubmissionRequest, opts ...grpc.CallOption) (*types.Submissions, error) {
	out := new(types.Submissions)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetSubmissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetSubmissionsByCourse(ctx context.Context, in *types.SubmissionsForCourseRequest, opts ...grpc.CallOption) (*types.CourseSubmissions, error) {
	out := new(types.CourseSubmissions)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetSubmissionsByCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateSubmission(ctx context.Context, in *types.UpdateSubmissionRequest, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateSubmission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateSubmissions(ctx context.Context, in *types.UpdateSubmissionsRequest, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateSubmissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) RebuildSubmissions(ctx context.Context, in *types.RebuildRequest, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/RebuildSubmissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) CreateBenchmark(ctx context.Context, in *types.GradingBenchmark, opts ...grpc.CallOption) (*types.GradingBenchmark, error) {
	out := new(types.GradingBenchmark)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/CreateBenchmark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateBenchmark(ctx context.Context, in *types.GradingBenchmark, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateBenchmark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) DeleteBenchmark(ctx context.Context, in *types.GradingBenchmark, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/DeleteBenchmark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) CreateCriterion(ctx context.Context, in *types.GradingCriterion, opts ...grpc.CallOption) (*types.GradingCriterion, error) {
	out := new(types.GradingCriterion)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/CreateCriterion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateCriterion(ctx context.Context, in *types.GradingCriterion, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateCriterion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) DeleteCriterion(ctx context.Context, in *types.GradingCriterion, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/DeleteCriterion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) CreateReview(ctx context.Context, in *types.ReviewRequest, opts ...grpc.CallOption) (*types.Review, error) {
	out := new(types.Review)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/CreateReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) UpdateReview(ctx context.Context, in *types.ReviewRequest, opts ...grpc.CallOption) (*types.Review, error) {
	out := new(types.Review)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/UpdateReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetReviewers(ctx context.Context, in *types.SubmissionReviewersRequest, opts ...grpc.CallOption) (*types.Reviewers, error) {
	out := new(types.Reviewers)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetReviewers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetProviders(ctx context.Context, in *types.Void, opts ...grpc.CallOption) (*types.Providers, error) {
	out := new(types.Providers)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetProviders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetOrganization(ctx context.Context, in *types.OrgRequest, opts ...grpc.CallOption) (*types.Organization, error) {
	out := new(types.Organization)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) GetRepositories(ctx context.Context, in *types.URLRequest, opts ...grpc.CallOption) (*types.Repositories, error) {
	out := new(types.Repositories)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/GetRepositories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickFeedServiceClient) IsEmptyRepo(ctx context.Context, in *types.RepositoryRequest, opts ...grpc.CallOption) (*types.Void, error) {
	out := new(types.Void)
	err := c.cc.Invoke(ctx, "/qf.QuickFeedService/IsEmptyRepo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuickFeedServiceServer is the server API for QuickFeedService service.
// All implementations must embed UnimplementedQuickFeedServiceServer
// for forward compatibility
type QuickFeedServiceServer interface {
	GetUser(context.Context, *types.Void) (*types.User, error)
	GetUsers(context.Context, *types.Void) (*types.Users, error)
	GetUserByCourse(context.Context, *types.CourseUserRequest) (*types.User, error)
	UpdateUser(context.Context, *types.User) (*types.Void, error)
	IsAuthorizedTeacher(context.Context, *types.Void) (*types.AuthorizationResponse, error)
	GetGroup(context.Context, *types.GetGroupRequest) (*types.Group, error)
	GetGroupByUserAndCourse(context.Context, *types.GroupRequest) (*types.Group, error)
	GetGroupsByCourse(context.Context, *types.CourseRequest) (*types.Groups, error)
	CreateGroup(context.Context, *types.Group) (*types.Group, error)
	UpdateGroup(context.Context, *types.Group) (*types.Group, error)
	DeleteGroup(context.Context, *types.GroupRequest) (*types.Void, error)
	GetCourse(context.Context, *types.CourseRequest) (*types.Course, error)
	GetCourses(context.Context, *types.Void) (*types.Courses, error)
	GetCoursesByUser(context.Context, *types.EnrollmentStatusRequest) (*types.Courses, error)
	CreateCourse(context.Context, *types.Course) (*types.Course, error)
	UpdateCourse(context.Context, *types.Course) (*types.Void, error)
	UpdateCourseVisibility(context.Context, *types.Enrollment) (*types.Void, error)
	GetAssignments(context.Context, *types.CourseRequest) (*types.Assignments, error)
	UpdateAssignments(context.Context, *types.CourseRequest) (*types.Void, error)
	GetEnrollmentsByUser(context.Context, *types.EnrollmentStatusRequest) (*types.Enrollments, error)
	GetEnrollmentsByCourse(context.Context, *types.EnrollmentRequest) (*types.Enrollments, error)
	CreateEnrollment(context.Context, *types.Enrollment) (*types.Void, error)
	UpdateEnrollments(context.Context, *types.Enrollments) (*types.Void, error)
	// Get latest submissions for all course assignments for a user or a group.
	GetSubmissions(context.Context, *types.SubmissionRequest) (*types.Submissions, error)
	// Get lab submissions for every course user or every course group
	GetSubmissionsByCourse(context.Context, *types.SubmissionsForCourseRequest) (*types.CourseSubmissions, error)
	UpdateSubmission(context.Context, *types.UpdateSubmissionRequest) (*types.Void, error)
	UpdateSubmissions(context.Context, *types.UpdateSubmissionsRequest) (*types.Void, error)
	RebuildSubmissions(context.Context, *types.RebuildRequest) (*types.Void, error)
	CreateBenchmark(context.Context, *types.GradingBenchmark) (*types.GradingBenchmark, error)
	UpdateBenchmark(context.Context, *types.GradingBenchmark) (*types.Void, error)
	DeleteBenchmark(context.Context, *types.GradingBenchmark) (*types.Void, error)
	CreateCriterion(context.Context, *types.GradingCriterion) (*types.GradingCriterion, error)
	UpdateCriterion(context.Context, *types.GradingCriterion) (*types.Void, error)
	DeleteCriterion(context.Context, *types.GradingCriterion) (*types.Void, error)
	CreateReview(context.Context, *types.ReviewRequest) (*types.Review, error)
	UpdateReview(context.Context, *types.ReviewRequest) (*types.Review, error)
	GetReviewers(context.Context, *types.SubmissionReviewersRequest) (*types.Reviewers, error)
	GetProviders(context.Context, *types.Void) (*types.Providers, error)
	GetOrganization(context.Context, *types.OrgRequest) (*types.Organization, error)
	GetRepositories(context.Context, *types.URLRequest) (*types.Repositories, error)
	IsEmptyRepo(context.Context, *types.RepositoryRequest) (*types.Void, error)
	mustEmbedUnimplementedQuickFeedServiceServer()
}

// UnimplementedQuickFeedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuickFeedServiceServer struct {
}

func (UnimplementedQuickFeedServiceServer) GetUser(context.Context, *types.Void) (*types.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetUsers(context.Context, *types.Void) (*types.Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetUserByCourse(context.Context, *types.CourseUserRequest) (*types.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByCourse not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateUser(context.Context, *types.User) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedQuickFeedServiceServer) IsAuthorizedTeacher(context.Context, *types.Void) (*types.AuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAuthorizedTeacher not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetGroup(context.Context, *types.GetGroupRequest) (*types.Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetGroupByUserAndCourse(context.Context, *types.GroupRequest) (*types.Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupByUserAndCourse not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetGroupsByCourse(context.Context, *types.CourseRequest) (*types.Groups, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupsByCourse not implemented")
}
func (UnimplementedQuickFeedServiceServer) CreateGroup(context.Context, *types.Group) (*types.Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateGroup(context.Context, *types.Group) (*types.Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedQuickFeedServiceServer) DeleteGroup(context.Context, *types.GroupRequest) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetCourse(context.Context, *types.CourseRequest) (*types.Course, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourse not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetCourses(context.Context, *types.Void) (*types.Courses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourses not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetCoursesByUser(context.Context, *types.EnrollmentStatusRequest) (*types.Courses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoursesByUser not implemented")
}
func (UnimplementedQuickFeedServiceServer) CreateCourse(context.Context, *types.Course) (*types.Course, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCourse not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateCourse(context.Context, *types.Course) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCourse not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateCourseVisibility(context.Context, *types.Enrollment) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCourseVisibility not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetAssignments(context.Context, *types.CourseRequest) (*types.Assignments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssignments not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateAssignments(context.Context, *types.CourseRequest) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssignments not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetEnrollmentsByUser(context.Context, *types.EnrollmentStatusRequest) (*types.Enrollments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnrollmentsByUser not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetEnrollmentsByCourse(context.Context, *types.EnrollmentRequest) (*types.Enrollments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnrollmentsByCourse not implemented")
}
func (UnimplementedQuickFeedServiceServer) CreateEnrollment(context.Context, *types.Enrollment) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnrollment not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateEnrollments(context.Context, *types.Enrollments) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEnrollments not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetSubmissions(context.Context, *types.SubmissionRequest) (*types.Submissions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubmissions not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetSubmissionsByCourse(context.Context, *types.SubmissionsForCourseRequest) (*types.CourseSubmissions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubmissionsByCourse not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateSubmission(context.Context, *types.UpdateSubmissionRequest) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubmission not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateSubmissions(context.Context, *types.UpdateSubmissionsRequest) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubmissions not implemented")
}
func (UnimplementedQuickFeedServiceServer) RebuildSubmissions(context.Context, *types.RebuildRequest) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildSubmissions not implemented")
}
func (UnimplementedQuickFeedServiceServer) CreateBenchmark(context.Context, *types.GradingBenchmark) (*types.GradingBenchmark, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBenchmark not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateBenchmark(context.Context, *types.GradingBenchmark) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBenchmark not implemented")
}
func (UnimplementedQuickFeedServiceServer) DeleteBenchmark(context.Context, *types.GradingBenchmark) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBenchmark not implemented")
}
func (UnimplementedQuickFeedServiceServer) CreateCriterion(context.Context, *types.GradingCriterion) (*types.GradingCriterion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCriterion not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateCriterion(context.Context, *types.GradingCriterion) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCriterion not implemented")
}
func (UnimplementedQuickFeedServiceServer) DeleteCriterion(context.Context, *types.GradingCriterion) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCriterion not implemented")
}
func (UnimplementedQuickFeedServiceServer) CreateReview(context.Context, *types.ReviewRequest) (*types.Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedQuickFeedServiceServer) UpdateReview(context.Context, *types.ReviewRequest) (*types.Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReview not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetReviewers(context.Context, *types.SubmissionReviewersRequest) (*types.Reviewers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviewers not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetProviders(context.Context, *types.Void) (*types.Providers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetOrganization(context.Context, *types.OrgRequest) (*types.Organization, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganization not implemented")
}
func (UnimplementedQuickFeedServiceServer) GetRepositories(context.Context, *types.URLRequest) (*types.Repositories, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepositories not implemented")
}
func (UnimplementedQuickFeedServiceServer) IsEmptyRepo(context.Context, *types.RepositoryRequest) (*types.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsEmptyRepo not implemented")
}
func (UnimplementedQuickFeedServiceServer) mustEmbedUnimplementedQuickFeedServiceServer() {}

// UnsafeQuickFeedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuickFeedServiceServer will
// result in compilation errors.
type UnsafeQuickFeedServiceServer interface {
	mustEmbedUnimplementedQuickFeedServiceServer()
}

func RegisterQuickFeedServiceServer(s grpc.ServiceRegistrar, srv QuickFeedServiceServer) {
	s.RegisterService(&QuickFeedService_ServiceDesc, srv)
}

func _QuickFeedService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetUser(ctx, req.(*types.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetUsers(ctx, req.(*types.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetUserByCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.CourseUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetUserByCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetUserByCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetUserByCourse(ctx, req.(*types.CourseUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateUser(ctx, req.(*types.User))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_IsAuthorizedTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).IsAuthorizedTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/IsAuthorizedTeacher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).IsAuthorizedTeacher(ctx, req.(*types.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetGroup(ctx, req.(*types.GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetGroupByUserAndCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetGroupByUserAndCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetGroupByUserAndCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetGroupByUserAndCourse(ctx, req.(*types.GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetGroupsByCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.CourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetGroupsByCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetGroupsByCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetGroupsByCourse(ctx, req.(*types.CourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).CreateGroup(ctx, req.(*types.Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateGroup(ctx, req.(*types.Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).DeleteGroup(ctx, req.(*types.GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.CourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetCourse(ctx, req.(*types.CourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetCourses(ctx, req.(*types.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetCoursesByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.EnrollmentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetCoursesByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetCoursesByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetCoursesByUser(ctx, req.(*types.EnrollmentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Course)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/CreateCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).CreateCourse(ctx, req.(*types.Course))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Course)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateCourse(ctx, req.(*types.Course))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateCourseVisibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Enrollment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateCourseVisibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateCourseVisibility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateCourseVisibility(ctx, req.(*types.Enrollment))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.CourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetAssignments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetAssignments(ctx, req.(*types.CourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.CourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateAssignments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateAssignments(ctx, req.(*types.CourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetEnrollmentsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.EnrollmentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetEnrollmentsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetEnrollmentsByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetEnrollmentsByUser(ctx, req.(*types.EnrollmentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetEnrollmentsByCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.EnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetEnrollmentsByCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetEnrollmentsByCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetEnrollmentsByCourse(ctx, req.(*types.EnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_CreateEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Enrollment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).CreateEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/CreateEnrollment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).CreateEnrollment(ctx, req.(*types.Enrollment))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Enrollments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateEnrollments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateEnrollments(ctx, req.(*types.Enrollments))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.SubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetSubmissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetSubmissions(ctx, req.(*types.SubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetSubmissionsByCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.SubmissionsForCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetSubmissionsByCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetSubmissionsByCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetSubmissionsByCourse(ctx, req.(*types.SubmissionsForCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.UpdateSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateSubmission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateSubmission(ctx, req.(*types.UpdateSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.UpdateSubmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateSubmissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateSubmissions(ctx, req.(*types.UpdateSubmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_RebuildSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.RebuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).RebuildSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/RebuildSubmissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).RebuildSubmissions(ctx, req.(*types.RebuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_CreateBenchmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GradingBenchmark)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).CreateBenchmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/CreateBenchmark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).CreateBenchmark(ctx, req.(*types.GradingBenchmark))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateBenchmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GradingBenchmark)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateBenchmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateBenchmark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateBenchmark(ctx, req.(*types.GradingBenchmark))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_DeleteBenchmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GradingBenchmark)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).DeleteBenchmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/DeleteBenchmark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).DeleteBenchmark(ctx, req.(*types.GradingBenchmark))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_CreateCriterion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GradingCriterion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).CreateCriterion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/CreateCriterion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).CreateCriterion(ctx, req.(*types.GradingCriterion))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateCriterion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GradingCriterion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateCriterion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateCriterion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateCriterion(ctx, req.(*types.GradingCriterion))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_DeleteCriterion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GradingCriterion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).DeleteCriterion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/DeleteCriterion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).DeleteCriterion(ctx, req.(*types.GradingCriterion))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/CreateReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).CreateReview(ctx, req.(*types.ReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_UpdateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).UpdateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/UpdateReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).UpdateReview(ctx, req.(*types.ReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetReviewers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.SubmissionReviewersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetReviewers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetReviewers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetReviewers(ctx, req.(*types.SubmissionReviewersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetProviders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetProviders(ctx, req.(*types.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.OrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetOrganization(ctx, req.(*types.OrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_GetRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.URLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).GetRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/GetRepositories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).GetRepositories(ctx, req.(*types.URLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickFeedService_IsEmptyRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.RepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickFeedServiceServer).IsEmptyRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qf.QuickFeedService/IsEmptyRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickFeedServiceServer).IsEmptyRepo(ctx, req.(*types.RepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuickFeedService_ServiceDesc is the grpc.ServiceDesc for QuickFeedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuickFeedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qf.QuickFeedService",
	HandlerType: (*QuickFeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _QuickFeedService_GetUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _QuickFeedService_GetUsers_Handler,
		},
		{
			MethodName: "GetUserByCourse",
			Handler:    _QuickFeedService_GetUserByCourse_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _QuickFeedService_UpdateUser_Handler,
		},
		{
			MethodName: "IsAuthorizedTeacher",
			Handler:    _QuickFeedService_IsAuthorizedTeacher_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _QuickFeedService_GetGroup_Handler,
		},
		{
			MethodName: "GetGroupByUserAndCourse",
			Handler:    _QuickFeedService_GetGroupByUserAndCourse_Handler,
		},
		{
			MethodName: "GetGroupsByCourse",
			Handler:    _QuickFeedService_GetGroupsByCourse_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _QuickFeedService_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _QuickFeedService_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _QuickFeedService_DeleteGroup_Handler,
		},
		{
			MethodName: "GetCourse",
			Handler:    _QuickFeedService_GetCourse_Handler,
		},
		{
			MethodName: "GetCourses",
			Handler:    _QuickFeedService_GetCourses_Handler,
		},
		{
			MethodName: "GetCoursesByUser",
			Handler:    _QuickFeedService_GetCoursesByUser_Handler,
		},
		{
			MethodName: "CreateCourse",
			Handler:    _QuickFeedService_CreateCourse_Handler,
		},
		{
			MethodName: "UpdateCourse",
			Handler:    _QuickFeedService_UpdateCourse_Handler,
		},
		{
			MethodName: "UpdateCourseVisibility",
			Handler:    _QuickFeedService_UpdateCourseVisibility_Handler,
		},
		{
			MethodName: "GetAssignments",
			Handler:    _QuickFeedService_GetAssignments_Handler,
		},
		{
			MethodName: "UpdateAssignments",
			Handler:    _QuickFeedService_UpdateAssignments_Handler,
		},
		{
			MethodName: "GetEnrollmentsByUser",
			Handler:    _QuickFeedService_GetEnrollmentsByUser_Handler,
		},
		{
			MethodName: "GetEnrollmentsByCourse",
			Handler:    _QuickFeedService_GetEnrollmentsByCourse_Handler,
		},
		{
			MethodName: "CreateEnrollment",
			Handler:    _QuickFeedService_CreateEnrollment_Handler,
		},
		{
			MethodName: "UpdateEnrollments",
			Handler:    _QuickFeedService_UpdateEnrollments_Handler,
		},
		{
			MethodName: "GetSubmissions",
			Handler:    _QuickFeedService_GetSubmissions_Handler,
		},
		{
			MethodName: "GetSubmissionsByCourse",
			Handler:    _QuickFeedService_GetSubmissionsByCourse_Handler,
		},
		{
			MethodName: "UpdateSubmission",
			Handler:    _QuickFeedService_UpdateSubmission_Handler,
		},
		{
			MethodName: "UpdateSubmissions",
			Handler:    _QuickFeedService_UpdateSubmissions_Handler,
		},
		{
			MethodName: "RebuildSubmissions",
			Handler:    _QuickFeedService_RebuildSubmissions_Handler,
		},
		{
			MethodName: "CreateBenchmark",
			Handler:    _QuickFeedService_CreateBenchmark_Handler,
		},
		{
			MethodName: "UpdateBenchmark",
			Handler:    _QuickFeedService_UpdateBenchmark_Handler,
		},
		{
			MethodName: "DeleteBenchmark",
			Handler:    _QuickFeedService_DeleteBenchmark_Handler,
		},
		{
			MethodName: "CreateCriterion",
			Handler:    _QuickFeedService_CreateCriterion_Handler,
		},
		{
			MethodName: "UpdateCriterion",
			Handler:    _QuickFeedService_UpdateCriterion_Handler,
		},
		{
			MethodName: "DeleteCriterion",
			Handler:    _QuickFeedService_DeleteCriterion_Handler,
		},
		{
			MethodName: "CreateReview",
			Handler:    _QuickFeedService_CreateReview_Handler,
		},
		{
			MethodName: "UpdateReview",
			Handler:    _QuickFeedService_UpdateReview_Handler,
		},
		{
			MethodName: "GetReviewers",
			Handler:    _QuickFeedService_GetReviewers_Handler,
		},
		{
			MethodName: "GetProviders",
			Handler:    _QuickFeedService_GetProviders_Handler,
		},
		{
			MethodName: "GetOrganization",
			Handler:    _QuickFeedService_GetOrganization_Handler,
		},
		{
			MethodName: "GetRepositories",
			Handler:    _QuickFeedService_GetRepositories_Handler,
		},
		{
			MethodName: "IsEmptyRepo",
			Handler:    _QuickFeedService_IsEmptyRepo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qf/qf.proto",
}
