package scm

const (
	getOrganizationsByID                                      = "GET /organizations/{id}"
	getOrgsByOrg                                              = "GET /orgs/{org}"
	patchOrgsByOrg                                            = "PATCH /orgs/{org}"
	getOrgsReposByOrg                                         = "GET /orgs/{org}/repos"
	postOrgsReposByOrg                                        = "POST /orgs/{org}/repos"
	getOrgsMembershipsByOrgByUsername                         = "GET /orgs/{org}/memberships/{username}"
	putOrgsMembershipsByOrgByUsername                         = "PUT /orgs/{org}/memberships/{username}"
	deleteOrgsMembersByOrgByUsername                          = "DELETE /orgs/{org}/members/{username}"
	getReposByOwnerByRepo                                     = "GET /repos/{owner}/{repo}"
	deleteReposByOwnerByRepo                                  = "DELETE /repos/{owner}/{repo}"
	getRepositoriesByID                                       = "GET /repositories/{repository_id}"
	getReposContentsByOwnerByRepoByPath                       = "GET /repos/{owner}/{repo}/contents/{path...}"
	getReposCollaboratorsByOwnerByRepo                        = "GET /repos/{owner}/{repo}/collaborators"
	putReposCollaboratorsByOwnerByRepoByUsername              = "PUT /repos/{owner}/{repo}/collaborators/{username}"
	deleteReposCollaboratorsByOwnerByRepoByUsername           = "DELETE /repos/{owner}/{repo}/collaborators/{username}"
	postReposIssuesByOwnerByRepo                              = "POST /repos/{owner}/{repo}/issues"
	patchReposIssuesByOwnerByRepoByIssueNumber                = "PATCH /repos/{owner}/{repo}/issues/{issue_number}"
	getReposIssuesByOwnerByRepoByIssueNumber                  = "GET /repos/{owner}/{repo}/issues/{issue_number}"
	getReposIssuesByOwnerByRepo                               = "GET /repos/{owner}/{repo}/issues"
	postReposIssuesCommentsByOwnerByRepoByIssueNumber         = "POST /repos/{owner}/{repo}/issues/{issue_number}/comments"
	patchReposIssuesCommentsByOwnerByRepoByCommentID          = "PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}"
	postReposPullsRequestedReviewersByOwnerByRepoByPullNumber = "POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers"
)
